server:
  port: 8787

spring:
  data:
    cassandra:
      keyspace-name: spring_cassandra
      contact-points:
        -   127.0.0.1
      port: 9042
      schema-action: create-if-not-exists
      local-datacenter: datacenter1

